# Generated by Django 6.0.2 on 2026-02-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=50, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('nss', models.CharField(max_length=11, unique=True, verbose_name='NSS')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('numero_exterior', models.CharField(max_length=10, verbose_name='Número Exterior')),
                ('numero_interior', models.CharField(blank=True, max_length=10, verbose_name='Número Interior')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo'), ('UL', 'Unión Libre')], max_length=2, verbose_name='Estado Civil')),
                ('contacto_emergencia_nombre', models.CharField(max_length=100, verbose_name='Contacto de Emergencia')),
                ('contacto_emergencia_telefono', models.CharField(max_length=15, verbose_name='Teléfono de Emergencia')),
                ('contacto_emergencia_parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
    ]
